language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pytest pytest-cov
  - pip install coveralls codecov
script:
  - pytest tests/test_sample.py
after_success:
  - coveralls
  - codecov
